theme                  : "minimal-mistakes-jekyll"
minimal_mistakes_skin    : "contrast"

# Site Settings
locale                   : "en-US"
title                    : SDG Metadata - Cambodia
title_separator          : "-"
subtitle                 : Machine Translation of Indicator Metadata for the Sustainable Development Goals
description              : Machine Translation of Indicator Metadata for the Sustainable Development Goals
url                      : # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : /translate-metadata
repository               : sdg-cambodia/translate-metadata
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/sdg-cambodia/translate-metadata

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  math_engine: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

display_main_nav: false

footer_scripts:
  - /assets/js/main.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/jsPlumb/2.8.6/js/jsplumb.js
  - https://unpkg.com/popper.js
  - https://unpkg.com/tooltip.js
  - /assets/js/custom.js
